#!/bin/bash

# 添加git commit配置
{
    git config  commit.template .git-commit-template.txt;
} || {
    git init;
    git config  commit.template .git-commit-template.txt;
}

# 将文件复制到 .git/hooks中去
cp -R .hooks/  .git/hooks